---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    app: ubuntu-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-client
  template:
    metadata:
      labels:
        app: ubuntu-client
      name: ubuntu-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: hr-client
        image: ubuntu
        resources:
          requests:
            cpu: 2
            memory: 10Gi
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            sleep 365d
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

