apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service0
    labels:
        name: config-service0
    namespace: hydragen
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":0.0020,"threads":1},"network_complexity":{"forward_requests":"synchronous","response_payload_size":512,"called_services":[{"service":"service1","port":80,"endpoint":"endpoint1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service0
    namespace: hydragen
    labels: {}
spec:
    selector:
        matchLabels:
            app: service0
            version: ""
    template:
        metadata:
            labels:
                app: service0
                version: ""
            annotations:
                sidecar.istio.io/bootstrapOverride: aeraki-bootstrap-config
                sidecar.istio.io/proxyImage: ghcr.io/aeraki-mesh/meta-protocol-proxy:1.4.1
                sidecar.istio.io/rewriteAppHTTPProbers: "false"
        spec:
            nodeName: worker1
            containers:
                - name: app
                  image: yizhengx/hydragen-emulator:d814de12
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: SERVICE_NAME
                      value: service0
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 1
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 2000m
                        memory: 1024M
                    requests:
                        cpu: 2000m
                        memory: 1024M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service0
---
apiVersion: v1
kind: Service
metadata:
    name: service0
    namespace: hydragen
    labels: {}
    annotations:
        http: /
spec:
    selector:
        app: service0
    ports:
        - name: http
          port: 80
          targetPort: 5000

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service1
    labels:
        name: config-service1
    namespace: hydragen
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":0.0020,"threads":1}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service1
    namespace: hydragen
    labels: {}
spec:
    selector:
        matchLabels:
            app: service1
            version: ""
    template:
        metadata:
            labels:
                app: service1
                version: ""
            annotations:
                sidecar.istio.io/bootstrapOverride: aeraki-bootstrap-config
                sidecar.istio.io/proxyImage: ghcr.io/aeraki-mesh/meta-protocol-proxy:1.4.1
                sidecar.istio.io/rewriteAppHTTPProbers: "false"
        spec:
            nodeName: worker1
            containers:
                - name: app
                  image: yizhengx/hydragen-emulator:d814de12
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: SERVICE_NAME
                      value: service1
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 1
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 5000m
                        memory: 1024M
                    requests:
                        cpu: 5000m
                        memory: 1024M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service1
---
apiVersion: v1
kind: Service
metadata:
    name: service1
    namespace: hydragen
    labels: {}
    annotations:
        http: /
spec:
    selector:
        app: service1
    ports:
        - name: http
          port: 80
          targetPort: 5000
